/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The versioned document a brief is assembled into. Web and email are renderers over this.
 */
export interface BriefObject {
  schema_version: number;
  brief_id: string;
  user_id: string;
  session_date: string;
  kind: "open" | "close";
  generated_at: string;
  subject: string;
  one_thing?: string | null;
  /**
   * Absent or null on the open brief, which carries no performance or P&L (M14). Always an object on the close brief.
   */
  book?: Book | null;
  sections: Section[];
  flags: Flag[];
  claims: Claim[];
  resolved_claims: Claim[];
  suppressed: string[];
  data_quality: {
    missing: string[];
    stale: string[];
  };
}
/**
 * All monetary values are integer cents. Never float.
 */
export interface Book {
  value_cents: number;
  day_pnl_cents: number;
  day_bps: number;
  total_pnl_cents: number;
  total_pct?: number;
  vs_spy_bps?: number;
}
export interface Section {
  id:
    | "one_thing"
    | "overnight_tape"
    | "premarket"
    | "calendar"
    | "sector_setup"
    | "exposure_check"
    | "scorecard"
    | "attribution"
    | "tape_quality"
    | "sector_rotation"
    | "after_hours"
    | "accountability";
  tier: "full" | "brief" | "suppressed";
  note?: string | null;
  rows: Row[];
}
export interface Row {
  /**
   * Absent on rows that name no security — a macro release in the open brief's calendar section has no ticker (M14).
   */
  symbol?: string | null;
  /**
   * Per-name suppression tier assigned by assembly (M5). Suppressed names are omitted from rows and listed in the top-level suppressed[] instead. Null on non-tiered rows (e.g. tape_quality, and the open brief's calendar / sector_setup).
   */
  tier?: "full" | "brief" | null;
  close?: number | null;
  day_return?: number | null;
  day_pnl_cents?: number | null;
  contribution_bps?: number | null;
  total_pnl_cents?: number | null;
  total_pct?: number | null;
  rvol?: number | null;
  range_position?: number | null;
  rel_strength?: number | null;
  /**
   * LLM-written. Prose only — must contain no figures.
   */
  why?: string | null;
  /**
   * Human-readable name for a row that isn't identified by its ticker (open brief §4 calendar, e.g. "CPI (Jul)").
   */
  label?: string | null;
  /**
   * Open brief §4 (calendar). Mirrors events.event_type.
   */
  event_type?: "earnings" | "lockup" | "ex_div" | "macro" | null;
  /**
   * Open brief §4 (calendar): the session date the event lands on.
   */
  occurs_at?: string | null;
  /**
   * Open brief §4 (calendar): whose calendar this is (docs/05).
   */
  tag?: "macro" | "holding" | "watchlist" | null;
  /**
   * Open brief §5 (sector setup): the sectors row this line summarizes.
   */
  sector_id?: string | null;
  /**
   * Open brief §5 (sector setup): the sector's display name.
   */
  name?: string | null;
  /**
   * Open brief §5 (sector setup): the sector's benchmark, or null when unset in the book.
   */
  benchmark_symbol?: string | null;
  /**
   * Open brief §5: the benchmark's trailing 5-session return.
   */
  ret_5d?: number | null;
  /**
   * Open brief §5: trailing 5-session return less SPY's over the same window.
   */
  vs_spy_5d?: number | null;
  /**
   * Open brief §5: the pre-market column. Always null in M14 — the feed lands in M15.
   */
  premarket?: number | null;
}
export interface Flag {
  type: "concentration" | "correlation" | "runway" | "dilution" | "earnings_soon" | "supply_event" | "short_interest";
  severity: "info" | "warn";
  symbol?: string | null;
  sector_id?: string | null;
  value?: number | null;
  text_key: string;
}
export interface Claim {
  id: string;
  symbol: string;
  type: "catalyst_pending" | "relative_strength" | "supply_overhang" | "breadth";
  direction: "up" | "down" | "neutral";
  horizon_sessions: number;
  outcome: "correct" | "wrong" | "unresolved" | null;
}
