/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The versioned document a brief is assembled into. Web and email are renderers over this.
 */
export interface BriefObject {
  schema_version: number;
  brief_id: string;
  user_id: string;
  session_date: string;
  kind: "open" | "close" | "open_cn" | "close_cn";
  generated_at: string;
  subject: string;
  /**
   * Optional; absent means USD. Stored pre-v7 bodies remain valid — this optionality is deliberate, so old renderers/bodies must keep working (docs/04).
   */
  currency?: "USD" | "CNY";
  one_thing?: string | null;
  /**
   * Absent or null on the open brief, which carries no performance or P&L (M14). Always an object on the close brief.
   */
  book?: Book | null;
  sections: Section[];
  flags: Flag[];
  claims: Claim[];
  resolved_claims: Claim[];
  suppressed: string[];
  data_quality: {
    missing: string[];
    stale: string[];
  };
}
/**
 * All monetary values are integer minor units (cents / fen). Never float.
 */
export interface Book {
  value_cents: number;
  day_pnl_cents: number;
  day_bps: number;
  total_pnl_cents: number;
  total_pct?: number;
  /**
   * vs the book's benchmark (SPY for the US book, CSI 300 for the CN book).
   */
  vs_spy_bps?: number;
}
export interface Section {
  id:
    | "one_thing"
    | "overnight_tape"
    | "premarket"
    | "calendar"
    | "sector_setup"
    | "exposure_check"
    | "scorecard"
    | "attribution"
    | "tape_quality"
    | "sector_rotation"
    | "after_hours"
    | "accountability"
    | "catalysts";
  tier: "full" | "brief" | "suppressed";
  note?: string | null;
  rows: Row[];
}
export interface Row {
  /**
   * Absent on rows that name no security — a macro release in the open brief's calendar section has no ticker (M14).
   */
  symbol?: string | null;
  /**
   * Per-name suppression tier assigned by assembly (M5). Suppressed names are omitted from rows and listed in the top-level suppressed[] instead. Null on non-tiered rows (e.g. tape_quality, and the open brief's calendar / sector_setup). Nullable via anyOf, not as an enum member — the absence of a tier is not itself a tier, and folding null into the enum makes the generated `.value` no longer a string.
   */
  tier?: ("full" | "brief") | null;
  close?: number | null;
  day_return?: number | null;
  day_pnl_cents?: number | null;
  contribution_bps?: number | null;
  total_pnl_cents?: number | null;
  total_pct?: number | null;
  rvol?: number | null;
  range_position?: number | null;
  rel_strength?: number | null;
  /**
   * LLM-written. Prose only — must contain no figures.
   */
  why?: string | null;
  /**
   * Attribution: market factor contribution to the day move, bps (M13).
   */
  market_bps?: number | null;
  /**
   * Attribution: theme factor contribution, bps (M13).
   */
  theme_bps?: number | null;
  /**
   * Attribution: idiosyncratic residual = total - market - theme, bps (M13).
   */
  resid_bps?: number | null;
  /**
   * Attribution: MAD-scaled residual z-score; salience (M13).
   */
  resid_z?: number | null;
  /**
   * Attribution row is a provisional PM score, not yet reconciled (M13).
   */
  provisional?: boolean | null;
  /**
   * Human-readable name for a row that isn't identified by its ticker (open brief §4 calendar, e.g. "CPI (Jul)").
   */
  label?: string | null;
  /**
   * Open brief §4 (calendar). Mirrors events.event_type.
   */
  event_type?: ("earnings" | "lockup" | "ex_div" | "macro") | null;
  /**
   * Open brief §4 (calendar): the session date the event lands on.
   */
  occurs_at?: string | null;
  /**
   * Open brief §4 (calendar): whose calendar this is (docs/05).
   */
  tag?: ("macro" | "holding" | "watchlist") | null;
  /**
   * Open brief §5 (sector setup): the sectors row this line summarizes.
   */
  sector_id?: string | null;
  /**
   * Open brief §5 (sector setup): the sector's display name.
   */
  name?: string | null;
  /**
   * Open brief §5 (sector setup): the sector's benchmark, or null when unset in the book.
   */
  benchmark_symbol?: string | null;
  /**
   * Open brief §5: the benchmark's trailing 5-session return.
   */
  ret_5d?: number | null;
  /**
   * Open brief §5: trailing 5-session return less SPY's over the same window.
   */
  vs_spy_5d?: number | null;
  /**
   * Open brief §5: the pre-market column. Always null in M14 — the feed lands in M15.
   */
  premarket?: number | null;
  /**
   * Open brief §2 (overnight tape): the symbol's overnight level — a futures price, a yield, an index level (M15).
   */
  level?: number | null;
  /**
   * Open brief §2: overnight change as a fraction, last vs prior close. Null for level-quoted symbols (10Y, VIX), where a percent change reads as noise and the absolute move is the figure (M15).
   */
  overnight_pct?: number | null;
  /**
   * Open brief §2: overnight change in the symbol's own units — index points, yield points, volatility points (M15).
   */
  overnight_abs?: number | null;
  /**
   * Open brief §3 (pre-market): extended_last vs prior close, as a fraction (M15).
   */
  pre_pct?: number | null;
  /**
   * Open brief §3: the pre-market gap in integer minor units (cents / fen). Money, not percent — a percent tells you nothing about what the position is worth (docs/01, M15).
   */
  gap_cents?: number | null;
  /**
   * Open brief §3: pre-market volume against the typical pre-market volume at the same point in the morning. Deliberately NOT `rvol` — pre-market volume is too thin for a 30-day daily-volume ratio to mean anything (D3, docs/05, M15).
   */
  premarket_vol_mult?: number | null;
  /**
   * Close brief catalysts: which feed produced the signal (M17). One row per signal, not per symbol — the renderer groups by symbol.
   */
  source?: ("insider" | "proposed" | "index" | "etf" | "lockup" | "eligibility") | null;
  /**
   * Close brief catalysts: the signal type within its source, e.g. `cluster`, `clevel_buy`, `large_144` (M17).
   */
  kind?: string | null;
  /**
   * Close brief catalysts: the date the signal is about — a transaction date, a filing date, a lockup expiry (M17).
   */
  ref_date?: string | null;
  /**
   * Close brief catalysts: distinct insiders in a cluster (M17).
   */
  insider_count?: number | null;
  /**
   * Close brief catalysts: transaction value in integer minor units (cents / fen). Never float (M17).
   */
  value_cents?: number | null;
  /**
   * Close brief catalysts: shares sold as a fraction of the insider's pre-transaction holding. Null when `shares_after` is unknown — the rule never assumes a denominator (M17).
   */
  pct_of_holding?: number | null;
  /**
   * Close brief catalysts: share count on a Form 144 proposal (M17).
   */
  shares?: number | null;
  /**
   * Close brief catalysts: proposed shares as a fraction of public float. Null renders as "size unknown" rather than the row being dropped — an unknown size is information (M17, open question 4).
   */
  pct_of_float?: number | null;
  /**
   * Close brief catalysts: trading days from an insider sale to the next known earnings date (M17).
   */
  days_to_event?: number | null;
  /**
   * Close brief catalysts: calendar days a Form 144 has gone unconverted (M17).
   */
  days_outstanding?: number | null;
  /**
   * Close brief catalysts: the vendor's transaction type did not map to a known Form 4 code, so tax withholding and option exercises could not be filtered. Severity is reduced by one and the row is annotated rather than silently included or dropped (M17, open question 2).
   */
  ambiguous_code?: boolean | null;
  /**
   * Close brief §4: signed distance of the close from its 20-session simple moving average, as a fraction (0.03 = 3% above). A distance, not the average itself, because distances are comparable across names and the average is not (M19).
   */
  ma20_dist?: number | null;
  /**
   * Close brief §4: signed distance of the close from its 50-session simple moving average, as a fraction. This is the `distance from 50d` column the content spec has carried since M5 and the design reference has always drawn (M19).
   */
  ma50_dist?: number | null;
  /**
   * Close brief §4: signed distance of the close from its 200-session simple moving average, as a fraction. Null until 200 sessions of adjusted history exist, which the default 90-day backfill does not provide (M19).
   */
  ma200_dist?: number | null;
  /**
   * Close brief §4: the trend regime in one word — `bullish` when 20 > 50 > 200, `bearish` when 20 < 50 < 200, `mixed` otherwise. Null until all three averages exist; a stack is a statement about the ordering of three numbers, which two of them cannot make (M19).
   */
  ma_stack?: ("bullish" | "bearish" | "mixed") | null;
  /**
   * Close brief §4: the session's volume over the mean of the 5 PRIOR sessions — `weekly` in trading days. The measured session is never in the denominator (verify-numbers check 6). Distinct from `rvol`, which is the 30-session ratio that drives suppression tiering and must not be conflated with it (M19).
   */
  vol_vs_5d?: number | null;
  /**
   * Close brief §4: the session's volume over the mean of the 21 PRIOR sessions — `monthly` in trading days. Same denominator rule as `vol_vs_5d` (M19).
   */
  vol_vs_21d?: number | null;
  /**
   * Close brief §4: 14-session average true range, in price. A simple mean of the true ranges, deliberately not Wilder's EMA — exact in Fraction and with no seeding convention to get wrong. Carried so a renderer can express distance to a level in ATR units, which is the only level distance comparable across names (M19).
   */
  atr14?: number | null;
  /**
   * Close brief §4: price of the nearest clustered level BELOW the close, on today's tape. Built from swing pivots and rolling extremes over 252 sessions, merged within half an ATR. Null when no such zone has been touched at least twice (M19).
   */
  support?: number | null;
  /**
   * Close brief §4: price of the nearest clustered level ABOVE the close, on today's tape. Same construction as `support` (M19).
   */
  resistance?: number | null;
  /**
   * Close brief §4: how many distinct sessions came within half an ATR of the support zone. Reported raw rather than folded into a strength score — `tested 4x` is auditable against bars_daily and a 0-100 composite is not (M19).
   */
  support_touches?: number | null;
  /**
   * Close brief §4: touch count for the resistance zone. See `support_touches` (M19).
   */
  resistance_touches?: number | null;
  /**
   * Close brief §4: the most recent session that touched the support zone. Carried because bounce probability decays with time, so recency is evidence in its own right (M19).
   */
  support_last_touch?: string | null;
  /**
   * Close brief §4: the most recent session that touched the resistance zone (M19).
   */
  resistance_last_touch?: string | null;
  /**
   * Close brief §4: highest adjusted high of the last 252 sessions, on today's tape. Null below a full year of history — a field named `52-week high` that is really a 40-week high is a lie (M19).
   */
  high_52w?: number | null;
  /**
   * Close brief §4: lowest adjusted low of the last 252 sessions, on today's tape. Same full-window rule as `high_52w` (M19).
   */
  low_52w?: number | null;
  /**
   * Close brief §4: `up` or `down` when the close went through a zone the prior close was on the other side of, the zone had at least two touches, AND the session's `rvol` exceeded the 1.5 spike threshold. An event, not a level; without the volume clause it fires on every drift across a line (M19).
   */
  breakout?: ("up" | "down") | null;
}
export interface Flag {
  type: "concentration" | "correlation" | "runway" | "dilution" | "earnings_soon" | "supply_event" | "short_interest";
  severity: "info" | "warn";
  symbol?: string | null;
  sector_id?: string | null;
  value?: number | null;
  text_key: string;
}
export interface Claim {
  id: string;
  symbol: string;
  type: "catalyst_pending" | "relative_strength" | "supply_overhang" | "breadth" | "premarket_gap";
  direction: "up" | "down" | "neutral";
  /**
   * Sessions until the claim is due. 0 is the open brief's morning claim, resolved at the same session's close — the same-day loop D16b built the engine for (M15).
   */
  horizon_sessions: number;
  outcome: "correct" | "wrong" | "unresolved" | null;
}
