/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The versioned document a brief is assembled into. Web and email are renderers over this.
 */
export interface BriefObject {
  schema_version: number;
  brief_id: string;
  user_id: string;
  session_date: string;
  kind: "open" | "close";
  generated_at: string;
  subject: string;
  one_thing?: string | null;
  /**
   * Absent or null on the open brief, which carries no performance or P&L (M14). Always an object on the close brief.
   */
  book?: Book | null;
  sections: Section[];
  flags: Flag[];
  claims: Claim[];
  resolved_claims: Claim[];
  suppressed: string[];
  data_quality: {
    missing: string[];
    stale: string[];
  };
}
/**
 * All monetary values are integer cents. Never float.
 */
export interface Book {
  value_cents: number;
  day_pnl_cents: number;
  day_bps: number;
  total_pnl_cents: number;
  total_pct?: number;
  vs_spy_bps?: number;
}
export interface Section {
  id:
    | "one_thing"
    | "overnight_tape"
    | "premarket"
    | "calendar"
    | "sector_setup"
    | "exposure_check"
    | "scorecard"
    | "attribution"
    | "tape_quality"
    | "sector_rotation"
    | "after_hours"
    | "accountability"
    | "catalysts";
  tier: "full" | "brief" | "suppressed";
  note?: string | null;
  rows: Row[];
}
export interface Row {
  /**
   * Absent on rows that name no security — a macro release in the open brief's calendar section has no ticker (M14).
   */
  symbol?: string | null;
  /**
   * Per-name suppression tier assigned by assembly (M5). Suppressed names are omitted from rows and listed in the top-level suppressed[] instead. Null on non-tiered rows (e.g. tape_quality, and the open brief's calendar / sector_setup). Nullable via anyOf, not as an enum member — the absence of a tier is not itself a tier, and folding null into the enum makes the generated `.value` no longer a string.
   */
  tier?: ("full" | "brief") | null;
  close?: number | null;
  day_return?: number | null;
  day_pnl_cents?: number | null;
  contribution_bps?: number | null;
  total_pnl_cents?: number | null;
  total_pct?: number | null;
  rvol?: number | null;
  range_position?: number | null;
  rel_strength?: number | null;
  /**
   * LLM-written. Prose only — must contain no figures.
   */
  why?: string | null;
  /**
   * Attribution: market factor contribution to the day move, bps (M13).
   */
  market_bps?: number | null;
  /**
   * Attribution: theme factor contribution, bps (M13).
   */
  theme_bps?: number | null;
  /**
   * Attribution: idiosyncratic residual = total - market - theme, bps (M13).
   */
  resid_bps?: number | null;
  /**
   * Attribution: MAD-scaled residual z-score; salience (M13).
   */
  resid_z?: number | null;
  /**
   * Attribution row is a provisional PM score, not yet reconciled (M13).
   */
  provisional?: boolean | null;
  /**
   * Human-readable name for a row that isn't identified by its ticker (open brief §4 calendar, e.g. "CPI (Jul)").
   */
  label?: string | null;
  /**
   * Open brief §4 (calendar). Mirrors events.event_type.
   */
  event_type?: ("earnings" | "lockup" | "ex_div" | "macro") | null;
  /**
   * Open brief §4 (calendar): the session date the event lands on.
   */
  occurs_at?: string | null;
  /**
   * Open brief §4 (calendar): whose calendar this is (docs/05).
   */
  tag?: ("macro" | "holding" | "watchlist") | null;
  /**
   * Open brief §5 (sector setup): the sectors row this line summarizes.
   */
  sector_id?: string | null;
  /**
   * Open brief §5 (sector setup): the sector's display name.
   */
  name?: string | null;
  /**
   * Open brief §5 (sector setup): the sector's benchmark, or null when unset in the book.
   */
  benchmark_symbol?: string | null;
  /**
   * Open brief §5: the benchmark's trailing 5-session return.
   */
  ret_5d?: number | null;
  /**
   * Open brief §5: trailing 5-session return less SPY's over the same window.
   */
  vs_spy_5d?: number | null;
  /**
   * Open brief §5: the pre-market column. Always null in M14 — the feed lands in M15.
   */
  premarket?: number | null;
  /**
   * Open brief §2 (overnight tape): the symbol's overnight level — a futures price, a yield, an index level (M15).
   */
  level?: number | null;
  /**
   * Open brief §2: overnight change as a fraction, last vs prior close. Null for level-quoted symbols (10Y, VIX), where a percent change reads as noise and the absolute move is the figure (M15).
   */
  overnight_pct?: number | null;
  /**
   * Open brief §2: overnight change in the symbol's own units — index points, yield points, volatility points (M15).
   */
  overnight_abs?: number | null;
  /**
   * Open brief §3 (pre-market): extended_last vs prior close, as a fraction (M15).
   */
  pre_pct?: number | null;
  /**
   * Open brief §3: the pre-market gap in integer cents. Dollars, not percent — a percent tells you nothing about what the position is worth (docs/01, M15).
   */
  gap_cents?: number | null;
  /**
   * Open brief §3: pre-market volume against the typical pre-market volume at the same point in the morning. Deliberately NOT `rvol` — pre-market volume is too thin for a 30-day daily-volume ratio to mean anything (D3, docs/05, M15).
   */
  premarket_vol_mult?: number | null;
  /**
   * Close brief catalysts: which feed produced the signal (M17). One row per signal, not per symbol — the renderer groups by symbol.
   */
  source?: ("insider" | "proposed" | "index" | "etf" | "lockup" | "eligibility") | null;
  /**
   * Close brief catalysts: the signal type within its source, e.g. `cluster`, `clevel_buy`, `large_144` (M17).
   */
  kind?: string | null;
  /**
   * Close brief catalysts: the date the signal is about — a transaction date, a filing date, a lockup expiry (M17).
   */
  ref_date?: string | null;
  /**
   * Close brief catalysts: distinct insiders in a cluster (M17).
   */
  insider_count?: number | null;
  /**
   * Close brief catalysts: transaction value in integer cents. Never float (M17).
   */
  value_cents?: number | null;
  /**
   * Close brief catalysts: shares sold as a fraction of the insider's pre-transaction holding. Null when `shares_after` is unknown — the rule never assumes a denominator (M17).
   */
  pct_of_holding?: number | null;
  /**
   * Close brief catalysts: share count on a Form 144 proposal (M17).
   */
  shares?: number | null;
  /**
   * Close brief catalysts: proposed shares as a fraction of public float. Null renders as "size unknown" rather than the row being dropped — an unknown size is information (M17, open question 4).
   */
  pct_of_float?: number | null;
  /**
   * Close brief catalysts: trading days from an insider sale to the next known earnings date (M17).
   */
  days_to_event?: number | null;
  /**
   * Close brief catalysts: calendar days a Form 144 has gone unconverted (M17).
   */
  days_outstanding?: number | null;
  /**
   * Close brief catalysts: the vendor's transaction type did not map to a known Form 4 code, so tax withholding and option exercises could not be filtered. Severity is reduced by one and the row is annotated rather than silently included or dropped (M17, open question 2).
   */
  ambiguous_code?: boolean | null;
}
export interface Flag {
  type: "concentration" | "correlation" | "runway" | "dilution" | "earnings_soon" | "supply_event" | "short_interest";
  severity: "info" | "warn";
  symbol?: string | null;
  sector_id?: string | null;
  value?: number | null;
  text_key: string;
}
export interface Claim {
  id: string;
  symbol: string;
  type: "catalyst_pending" | "relative_strength" | "supply_overhang" | "breadth" | "premarket_gap";
  direction: "up" | "down" | "neutral";
  /**
   * Sessions until the claim is due. 0 is the open brief's morning claim, resolved at the same session's close — the same-day loop D16b built the engine for (M15).
   */
  horizon_sessions: number;
  outcome: "correct" | "wrong" | "unresolved" | null;
}
