# generated by datamodel-codegen:
#   filename:  brief-object.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class Kind(Enum):
    open = 'open'
    close = 'close'
    open_cn = 'open_cn'
    close_cn = 'close_cn'


class Currency(Enum):
    USD = 'USD'
    CNY = 'CNY'


class DataQuality(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    missing: list[str]
    stale: list[str]


class Book(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value_cents: int
    day_pnl_cents: int
    day_bps: int
    total_pnl_cents: int
    total_pct: float | None = None
    vs_spy_bps: int | None = Field(
        None,
        description="vs the book's benchmark (SPY for the US book, CSI 300 for the CN book).",
    )


class Id(Enum):
    one_thing = 'one_thing'
    overnight_tape = 'overnight_tape'
    premarket = 'premarket'
    calendar = 'calendar'
    sector_setup = 'sector_setup'
    exposure_check = 'exposure_check'
    scorecard = 'scorecard'
    attribution = 'attribution'
    tape_quality = 'tape_quality'
    sector_rotation = 'sector_rotation'
    after_hours = 'after_hours'
    accountability = 'accountability'
    catalysts = 'catalysts'


class Tier(Enum):
    full = 'full'
    brief = 'brief'
    suppressed = 'suppressed'


class Tier1(Enum):
    full = 'full'
    brief = 'brief'


class EventType(Enum):
    earnings = 'earnings'
    lockup = 'lockup'
    ex_div = 'ex_div'
    macro = 'macro'


class Tag(Enum):
    macro = 'macro'
    holding = 'holding'
    watchlist = 'watchlist'


class Source(Enum):
    insider = 'insider'
    proposed = 'proposed'
    index = 'index'
    etf = 'etf'
    lockup = 'lockup'
    eligibility = 'eligibility'


class Row(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: str | None = Field(
        None,
        description="Absent on rows that name no security — a macro release in the open brief's calendar section has no ticker (M14).",
    )
    tier: Tier1 | None = Field(
        None,
        description="Per-name suppression tier assigned by assembly (M5). Suppressed names are omitted from rows and listed in the top-level suppressed[] instead. Null on non-tiered rows (e.g. tape_quality, and the open brief's calendar / sector_setup). Nullable via anyOf, not as an enum member — the absence of a tier is not itself a tier, and folding null into the enum makes the generated `.value` no longer a string.",
    )
    close: float | None = None
    day_return: float | None = None
    day_pnl_cents: int | None = None
    contribution_bps: int | None = None
    total_pnl_cents: int | None = None
    total_pct: float | None = None
    rvol: float | None = None
    range_position: confloat(ge=0.0, le=1.0) | None = None
    rel_strength: float | None = None
    why: str | None = Field(
        None, description='LLM-written. Prose only — must contain no figures.'
    )
    market_bps: int | None = Field(
        None,
        description='Attribution: market factor contribution to the day move, bps (M13).',
    )
    theme_bps: int | None = Field(
        None, description='Attribution: theme factor contribution, bps (M13).'
    )
    resid_bps: int | None = Field(
        None,
        description='Attribution: idiosyncratic residual = total - market - theme, bps (M13).',
    )
    resid_z: float | None = Field(
        None, description='Attribution: MAD-scaled residual z-score; salience (M13).'
    )
    provisional: bool | None = Field(
        None,
        description='Attribution row is a provisional PM score, not yet reconciled (M13).',
    )
    label: str | None = Field(
        None,
        description='Human-readable name for a row that isn\'t identified by its ticker (open brief §4 calendar, e.g. "CPI (Jul)").',
    )
    event_type: EventType | None = Field(
        None, description='Open brief §4 (calendar). Mirrors events.event_type.'
    )
    occurs_at: date | None = Field(
        None,
        description='Open brief §4 (calendar): the session date the event lands on.',
    )
    tag: Tag | None = Field(
        None, description='Open brief §4 (calendar): whose calendar this is (docs/05).'
    )
    sector_id: str | None = Field(
        None,
        description='Open brief §5 (sector setup): the sectors row this line summarizes.',
    )
    name: str | None = Field(
        None, description="Open brief §5 (sector setup): the sector's display name."
    )
    benchmark_symbol: str | None = Field(
        None,
        description="Open brief §5 (sector setup): the sector's benchmark, or null when unset in the book.",
    )
    ret_5d: float | None = Field(
        None, description="Open brief §5: the benchmark's trailing 5-session return."
    )
    vs_spy_5d: float | None = Field(
        None,
        description="Open brief §5: trailing 5-session return less SPY's over the same window.",
    )
    premarket: float | None = Field(
        None,
        description='Open brief §5: the pre-market column. Always null in M14 — the feed lands in M15.',
    )
    level: float | None = Field(
        None,
        description="Open brief §2 (overnight tape): the symbol's overnight level — a futures price, a yield, an index level (M15).",
    )
    overnight_pct: float | None = Field(
        None,
        description='Open brief §2: overnight change as a fraction, last vs prior close. Null for level-quoted symbols (10Y, VIX), where a percent change reads as noise and the absolute move is the figure (M15).',
    )
    overnight_abs: float | None = Field(
        None,
        description="Open brief §2: overnight change in the symbol's own units — index points, yield points, volatility points (M15).",
    )
    pre_pct: float | None = Field(
        None,
        description='Open brief §3 (pre-market): extended_last vs prior close, as a fraction (M15).',
    )
    gap_cents: int | None = Field(
        None,
        description='Open brief §3: the pre-market gap in integer minor units (cents / fen). Money, not percent — a percent tells you nothing about what the position is worth (docs/01, M15).',
    )
    premarket_vol_mult: float | None = Field(
        None,
        description='Open brief §3: pre-market volume against the typical pre-market volume at the same point in the morning. Deliberately NOT `rvol` — pre-market volume is too thin for a 30-day daily-volume ratio to mean anything (D3, docs/05, M15).',
    )
    source: Source | None = Field(
        None,
        description='Close brief catalysts: which feed produced the signal (M17). One row per signal, not per symbol — the renderer groups by symbol.',
    )
    kind: str | None = Field(
        None,
        description='Close brief catalysts: the signal type within its source, e.g. `cluster`, `clevel_buy`, `large_144` (M17).',
    )
    ref_date: date | None = Field(
        None,
        description='Close brief catalysts: the date the signal is about — a transaction date, a filing date, a lockup expiry (M17).',
    )
    insider_count: int | None = Field(
        None, description='Close brief catalysts: distinct insiders in a cluster (M17).'
    )
    value_cents: int | None = Field(
        None,
        description='Close brief catalysts: transaction value in integer minor units (cents / fen). Never float (M17).',
    )
    pct_of_holding: float | None = Field(
        None,
        description="Close brief catalysts: shares sold as a fraction of the insider's pre-transaction holding. Null when `shares_after` is unknown — the rule never assumes a denominator (M17).",
    )
    shares: float | None = Field(
        None,
        description='Close brief catalysts: share count on a Form 144 proposal (M17).',
    )
    pct_of_float: float | None = Field(
        None,
        description='Close brief catalysts: proposed shares as a fraction of public float. Null renders as "size unknown" rather than the row being dropped — an unknown size is information (M17, open question 4).',
    )
    days_to_event: int | None = Field(
        None,
        description='Close brief catalysts: trading days from an insider sale to the next known earnings date (M17).',
    )
    days_outstanding: int | None = Field(
        None,
        description='Close brief catalysts: calendar days a Form 144 has gone unconverted (M17).',
    )
    ambiguous_code: bool | None = Field(
        None,
        description="Close brief catalysts: the vendor's transaction type did not map to a known Form 4 code, so tax withholding and option exercises could not be filtered. Severity is reduced by one and the row is annotated rather than silently included or dropped (M17, open question 2).",
    )


class Type(Enum):
    concentration = 'concentration'
    correlation = 'correlation'
    runway = 'runway'
    dilution = 'dilution'
    earnings_soon = 'earnings_soon'
    supply_event = 'supply_event'
    short_interest = 'short_interest'


class Severity(Enum):
    info = 'info'
    warn = 'warn'


class Flag(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    severity: Severity
    symbol: str | None = None
    sector_id: str | None = None
    value: float | None = None
    text_key: str


class Type1(Enum):
    catalyst_pending = 'catalyst_pending'
    relative_strength = 'relative_strength'
    supply_overhang = 'supply_overhang'
    breadth = 'breadth'
    premarket_gap = 'premarket_gap'


class Direction(Enum):
    up = 'up'
    down = 'down'
    neutral = 'neutral'


class Outcome(Enum):
    correct = 'correct'
    wrong = 'wrong'
    unresolved = 'unresolved'
    NoneType_None = None


class Claim(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    symbol: str
    type: Type1
    direction: Direction
    horizon_sessions: conint(ge=0) = Field(
        ...,
        description="Sessions until the claim is due. 0 is the open brief's morning claim, resolved at the same session's close — the same-day loop D16b built the engine for (M15).",
    )
    outcome: Outcome


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    tier: Tier
    note: str | None = None
    rows: list[Row]


class BriefObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: conint(ge=1)
    brief_id: str
    user_id: str
    session_date: date
    kind: Kind
    generated_at: AwareDatetime
    subject: constr(max_length=160)
    currency: Currency | None = Field(
        None,
        description='Optional; absent means USD. Stored pre-v7 bodies remain valid — this optionality is deliberate, so old renderers/bodies must keep working (docs/04).',
    )
    one_thing: str | None = None
    book: Book | None = Field(
        None,
        description='Absent or null on the open brief, which carries no performance or P&L (M14). Always an object on the close brief.',
    )
    sections: list[Section]
    flags: list[Flag]
    claims: list[Claim]
    resolved_claims: list[Claim]
    suppressed: list[str]
    data_quality: DataQuality
