# generated by datamodel-codegen:
#   filename:  brief-object.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class Kind(Enum):
    open = 'open'
    close = 'close'


class DataQuality(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    missing: list[str]
    stale: list[str]


class Book(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value_cents: int
    day_pnl_cents: int
    day_bps: int
    total_pnl_cents: int
    total_pct: float | None = None
    vs_spy_bps: int | None = None


class Id(Enum):
    one_thing = 'one_thing'
    overnight_tape = 'overnight_tape'
    premarket = 'premarket'
    calendar = 'calendar'
    sector_setup = 'sector_setup'
    exposure_check = 'exposure_check'
    scorecard = 'scorecard'
    attribution = 'attribution'
    tape_quality = 'tape_quality'
    sector_rotation = 'sector_rotation'
    after_hours = 'after_hours'
    accountability = 'accountability'


class Tier(Enum):
    full = 'full'
    brief = 'brief'
    suppressed = 'suppressed'


class Tier1(Enum):
    full = 'full'
    brief = 'brief'


class EventType(Enum):
    earnings = 'earnings'
    lockup = 'lockup'
    ex_div = 'ex_div'
    macro = 'macro'
    NoneType_None = None


class Tag(Enum):
    macro = 'macro'
    holding = 'holding'
    watchlist = 'watchlist'
    NoneType_None = None


class Row(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: str | None = Field(
        None,
        description="Absent on rows that name no security — a macro release in the open brief's calendar section has no ticker (M14).",
    )
    tier: Tier1 | None = Field(
        None,
        description='Per-name suppression tier assigned by assembly (M5). Suppressed names are omitted from rows and listed in the top-level suppressed[] instead. Absent on non-tiered rows (e.g. tape_quality).',
    )
    close: float | None = None
    day_return: float | None = None
    day_pnl_cents: int | None = None
    contribution_bps: int | None = None
    total_pnl_cents: int | None = None
    total_pct: float | None = None
    rvol: float | None = None
    range_position: confloat(ge=0.0, le=1.0) | None = None
    rel_strength: float | None = None
    why: str | None = Field(
        None, description='LLM-written. Prose only — must contain no figures.'
    )
    label: str | None = Field(
        None,
        description='Human-readable name for a row that isn\'t identified by its ticker (open brief §4 calendar, e.g. "CPI (Jul)").',
    )
    event_type: EventType | None = Field(
        None, description='Open brief §4 (calendar). Mirrors events.event_type.'
    )
    occurs_at: date | None = Field(
        None,
        description='Open brief §4 (calendar): the session date the event lands on.',
    )
    tag: Tag | None = Field(
        None, description='Open brief §4 (calendar): whose calendar this is (docs/05).'
    )
    sector_id: str | None = Field(
        None,
        description='Open brief §5 (sector setup): the sectors row this line summarizes.',
    )
    name: str | None = Field(
        None, description="Open brief §5 (sector setup): the sector's display name."
    )
    benchmark_symbol: str | None = Field(
        None,
        description="Open brief §5 (sector setup): the sector's benchmark, or null when unset in the book.",
    )
    ret_5d: float | None = Field(
        None, description="Open brief §5: the benchmark's trailing 5-session return."
    )
    vs_spy_5d: float | None = Field(
        None,
        description="Open brief §5: trailing 5-session return less SPY's over the same window.",
    )
    premarket: float | None = Field(
        None,
        description='Open brief §5: the pre-market column. Always null in M14 — the feed lands in M15.',
    )


class Type(Enum):
    concentration = 'concentration'
    correlation = 'correlation'
    runway = 'runway'
    dilution = 'dilution'
    earnings_soon = 'earnings_soon'
    supply_event = 'supply_event'
    short_interest = 'short_interest'


class Severity(Enum):
    info = 'info'
    warn = 'warn'


class Flag(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    severity: Severity
    symbol: str | None = None
    sector_id: str | None = None
    value: float | None = None
    text_key: str


class Type1(Enum):
    catalyst_pending = 'catalyst_pending'
    relative_strength = 'relative_strength'
    supply_overhang = 'supply_overhang'
    breadth = 'breadth'


class Direction(Enum):
    up = 'up'
    down = 'down'
    neutral = 'neutral'


class Outcome(Enum):
    correct = 'correct'
    wrong = 'wrong'
    unresolved = 'unresolved'
    NoneType_None = None


class Claim(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    symbol: str
    type: Type1
    direction: Direction
    horizon_sessions: conint(ge=1)
    outcome: Outcome


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    tier: Tier
    note: str | None = None
    rows: list[Row]


class BriefObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: conint(ge=1)
    brief_id: str
    user_id: str
    session_date: date
    kind: Kind
    generated_at: AwareDatetime
    subject: constr(max_length=160)
    one_thing: str | None = None
    book: Book | None = Field(
        None,
        description='Absent on the open brief, which carries no performance or P&L (M14). Always present on the close brief.',
    )
    sections: list[Section]
    flags: list[Flag]
    claims: list[Claim]
    resolved_claims: list[Claim]
    suppressed: list[str]
    data_quality: DataQuality
